import { writeFileSync } from 'node:fs';
import { artworks, visibleArtworks, hiddenArtworks } from '../data/artworks.js';

const MIN_ASPECT_RATIO = 0.55;
const MAX_ASPECT_RATIO = 1.95;
const MIN_LONG_EDGE = 1200;
const MIN_SHORT_EDGE = 700;
const ALLOWED_MIME = new Set(['image/jpeg', 'image/png', 'image/webp']);
const BATCH_SIZE = 20;

function normalizeFileTitle(fileTitle) {
  const trimmed = String(fileTitle || '').trim();
  if (!trimmed) {
    throw new Error('Missing Wikimedia Commons file title');
  }
  return trimmed.startsWith('File:') ? trimmed : `File:${trimmed}`;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchJson(url, attempt = 0) {
  const response = await fetch(url);
  const text = await response.text();

  if (response.status === 429 || text.startsWith('You are making too many requests')) {
    if (attempt >= 8) {
      throw new Error('Wikimedia request failed: 429');
    }
    await sleep(3000 * (attempt + 1));
    return fetchJson(url, attempt + 1);
  }

  if (!response.ok) {
    throw new Error(`Wikimedia request failed: ${response.status}`);
  }

  return JSON.parse(text);
}

async function fetchImageInfoBatch(fileTitles) {
  const titles = fileTitles.map(normalizeFileTitle).join('|');
  const params = new URLSearchParams({
    action: 'query',
    titles,
    redirects: '1',
    prop: 'imageinfo',
    iiprop: 'url|mime|size|extmetadata',
    format: 'json',
    formatversion: '2',
    origin: '*',
  });

  const data = await fetchJson(
    `https://commons.wikimedia.org/w/api.php?${params.toString()}`
  );

  const pages = data?.query?.pages || [];
  const normalizedToResult = new Map();

  const redirects = new Map(
    (data?.query?.redirects || []).map((item) => [item.from, item.to])
  );
  const normalized = new Map(
    (data?.query?.normalized || []).map((item) => [item.from, item.to])
  );

  function resolveRequestedTitle(requested) {
    let current = requested;
    if (normalized.has(current)) current = normalized.get(current);
    if (redirects.has(current)) current = redirects.get(current);
    return current;
  }

  for (const requested of fileTitles) {
    const requestedTitle = normalizeFileTitle(requested);
    const resolvedTitle = resolveRequestedTitle(requestedTitle);
    const page =
      pages.find((item) => item.title === resolvedTitle) ||
      pages.find((item) => item.title === requestedTitle);

    if (!page || page.missing || !page.imageinfo?.[0]) {
      normalizedToResult.set(requested, {
        error: `Exact Wikimedia Commons file was not found: ${requestedTitle}`,
      });
      continue;
    }

    normalizedToResult.set(requested, {
      returnedTitle: page.title.replace(/^File:/, ''),
      info: page.imageinfo[0],
    });
  }

  return normalizedToResult;
}

function validateInfo(artwork, returnedTitle, info) {
  const failures = [];

  if (!ALLOWED_MIME.has(info.mime)) {
    failures.push(`unsupported mime ${info.mime}`);
  }

  const width = Number(info.width || 0);
  const height = Number(info.height || 0);

  if (!width || !height) {
    failures.push('missing dimensions');
  }

  const longEdge = Math.max(width, height);
  const shortEdge = Math.min(width, height);
  const aspectRatio = width && height ? width / height : NaN;

  if (longEdge < MIN_LONG_EDGE || shortEdge < MIN_SHORT_EDGE) {
    failures.push(`resolution too small (${width}×${height})`);
  }

  if (
    Number.isFinite(aspectRatio) &&
    (aspectRatio < MIN_ASPECT_RATIO || aspectRatio > MAX_ASPECT_RATIO)
  ) {
    failures.push(`aspect ratio out of range (${aspectRatio.toFixed(3)})`);
  }

  return {
    id: artwork.id,
    titleZh: artwork.titleZh,
    artist: artwork.artist,
    hidden: Boolean(artwork.hidden),
    commonsFile: artwork.commonsFile,
    returnedTitle,
    width,
    height,
    aspectRatio: Number.isFinite(aspectRatio) ? Number(aspectRatio.toFixed(3)) : null,
    source: info.descriptionurl || '',
    mime: info.mime || '',
    status: failures.length ? 'FAIL' : 'PASS',
    failures,
  };
}

function printRow(result) {
  const size =
    result.width && result.height ? `${result.width}×${result.height}` : 'n/a';
  const ar = result.aspectRatio == null ? 'n/a' : String(result.aspectRatio);
  console.log(
    [
      result.status,
      result.id,
      result.titleZh,
      result.artist,
      result.commonsFile,
      result.returnedTitle || '(missing)',
      size,
      ar,
      result.source || '(none)',
      result.failures.length ? result.failures.join('; ') : 'ok',
    ].join(' | ')
  );
}

function toMarkdown(results, structuralFailures) {
  const passed = results.filter((item) => item.status === 'PASS').length;
  const lines = [
    '# Image Audit Report',
    '',
    `Generated by \`node scripts/audit-commons.mjs\`.`,
    '',
    `- Total artworks: ${artworks.length}`,
    `- Visible: ${visibleArtworks.length}`,
    `- Hidden: ${hiddenArtworks.length}`,
    `- PASS: ${passed}/${results.length}`,
    `- FAIL: ${results.length - passed}/${results.length}`,
    '',
  ];

  if (structuralFailures.length) {
    lines.push('## Structural checks', '');
    structuralFailures.forEach((item) => lines.push(`- FAIL: ${item}`));
    lines.push('');
  }

  lines.push('## Per-artwork results', '');

  for (const result of results) {
    lines.push(`### ${result.titleZh} (\`${result.id}\`)`);
    lines.push('');
    lines.push(`- Status: **${result.status}**`);
    lines.push(`- Artist: ${result.artist}`);
    lines.push(`- Collection: ${result.hidden ? 'hidden' : 'visible'}`);
    lines.push(`- commonsFile: \`${result.commonsFile}\``);
    lines.push(`- Returned file: \`${result.returnedTitle || '(missing)'}\``);
    lines.push(
      `- Original size: ${
        result.width && result.height ? `${result.width}×${result.height}` : 'n/a'
      }`
    );
    lines.push(
      `- Aspect ratio: ${result.aspectRatio == null ? 'n/a' : result.aspectRatio}`
    );
    lines.push(`- MIME: ${result.mime || 'n/a'}`);
    lines.push(
      `- Source: ${result.source ? `[Commons page](${result.source})` : 'n/a'}`
    );
    if (result.failures.length) {
      lines.push(`- Failures: ${result.failures.join('; ')}`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trim()}\n`;
}

const results = [];
const structuralFailures = [];

if (artworks.length !== 54) {
  structuralFailures.push(`Expected 54 artworks, found ${artworks.length}`);
}
if (visibleArtworks.length !== 48) {
  structuralFailures.push(
    `Expected 48 visible artworks, found ${visibleArtworks.length}`
  );
}
if (hiddenArtworks.length !== 6) {
  structuralFailures.push(
    `Expected 6 hidden artworks, found ${hiddenArtworks.length}`
  );
}

const missingFiles = artworks.filter((item) => !item.commonsFile);
if (missingFiles.length) {
  structuralFailures.push(
    `Missing commonsFile: ${missingFiles.map((item) => item.id).join(', ')}`
  );
}

const fileNames = artworks.map((item) => item.commonsFile).filter(Boolean);
const duplicates = fileNames.filter(
  (name, index) => fileNames.indexOf(name) !== index
);
if (duplicates.length) {
  structuralFailures.push(
    `Duplicate commonsFile values: ${[...new Set(duplicates)].join(', ')}`
  );
}

console.log('Soul Gallery Commons image audit');
console.log(
  `Artworks: ${artworks.length} | Visible: ${visibleArtworks.length} | Hidden: ${hiddenArtworks.length}`
);
console.log('---');

for (let index = 0; index < artworks.length; index += BATCH_SIZE) {
  const batch = artworks.slice(index, index + BATCH_SIZE);
  const batchMap = await fetchImageInfoBatch(batch.map((item) => item.commonsFile));

  for (const artwork of batch) {
    const payload = batchMap.get(artwork.commonsFile);
    let result;

    if (!payload || payload.error) {
      result = {
        id: artwork.id,
        titleZh: artwork.titleZh,
        artist: artwork.artist,
        hidden: Boolean(artwork.hidden),
        commonsFile: artwork.commonsFile || '',
        returnedTitle: '',
        width: null,
        height: null,
        aspectRatio: null,
        source: '',
        mime: '',
        status: 'FAIL',
        failures: [payload?.error || 'Unknown batch lookup failure'],
      };
    } else {
      result = validateInfo(artwork, payload.returnedTitle, payload.info);
    }

    results.push(result);
    printRow(result);
  }

  if (index + BATCH_SIZE < artworks.length) {
    await sleep(1200);
  }
}

const failed = results.filter((item) => item.status === 'FAIL');
const passed = results.filter((item) => item.status === 'PASS');

console.log('---');
console.log(`PASS: ${passed.length}/${results.length}`);
console.log(`FAIL: ${failed.length}/${results.length}`);

if (structuralFailures.length) {
  console.log('Structural failures:');
  structuralFailures.forEach((item) => console.log(`- ${item}`));
}

writeFileSync(
  new URL('../IMAGE_AUDIT.md', import.meta.url),
  toMarkdown(results, structuralFailures)
);
console.log('Wrote IMAGE_AUDIT.md');

if (failed.length || structuralFailures.length) {
  process.exit(1);
}
